-- Generated from generator/demo_specs/aws-thailand-tourism-guest-360.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-thailand-tourism-guest-360
-- This is the schema that is actually deployed for THAILAND_TOURISM_GUEST_360.

-- Alerts fire on the bottom tail of Repeat Rate
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_REPEAT_RATE) AS T
  FROM RAW.STAY_HISTORY
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_REPEAT_RATE <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_REPEAT_RATE), 2) AS AVG_REPEAT_RATE,
  ROUND(AVG(f.KPI_NPS_SCORE), 2) AS AVG_NPS_SCORE,
  ROUND(AVG(f.KPI_OFFER_CONVERSION), 2) AS AVG_OFFER_CONVERSION,
  ROUND(AVG(f.KPI_APP_ENGAGEMENT), 2) AS AVG_APP_ENGAGEMENT
FROM RAW.STAY_HISTORY f
JOIN RAW.THAI_TOURISM_TRENDS e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_REPEAT_RATE), 2) AS AVG_REPEAT_RATE,
  ROUND(AVG(f.KPI_NPS_SCORE), 2) AS AVG_NPS_SCORE,
  ROUND(AVG(f.KPI_OFFER_CONVERSION), 2) AS AVG_OFFER_CONVERSION,
  ROUND(AVG(f.KPI_APP_ENGAGEMENT), 2) AS AVG_APP_ENGAGEMENT
FROM RAW.STAY_HISTORY f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_REPEAT_RATE) AS KPI_REPEAT_RATE, AVG(KPI_NPS_SCORE) AS KPI_NPS_SCORE, AVG(KPI_OFFER_CONVERSION) AS KPI_OFFER_CONVERSION, AVG(KPI_APP_ENGAGEMENT) AS KPI_APP_ENGAGEMENT FROM RAW.STAY_HISTORY),
     en AS (SELECT SUM(KPI_GUEST_PROFILES) AS KPI_GUEST_PROFILES, SUM(KPI_ACTIVE_CAMPAIGNS) AS KPI_ACTIVE_CAMPAIGNS, SUM(KPI_UPSELL_REVENUE) AS KPI_UPSELL_REVENUE FROM RAW.THAI_TOURISM_TRENDS)
  SELECT 1 AS SORT_ORDER, 'Guest Profiles' AS TITLE, KPI_GUEST_PROFILES AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_GUEST_PROFILES) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Repeat Rate' AS TITLE, KPI_REPEAT_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_REPEAT_RATE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'NPS Score' AS TITLE, KPI_NPS_SCORE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_NPS_SCORE)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Active Campaigns' AS TITLE, KPI_ACTIVE_CAMPAIGNS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_ACTIVE_CAMPAIGNS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Offer Conversion' AS TITLE, KPI_OFFER_CONVERSION AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_OFFER_CONVERSION), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Upsell Revenue' AS TITLE, KPI_UPSELL_REVENUE AS VALUE_NUM, '฿' || TO_VARCHAR(CAST(ROUND(((KPI_UPSELL_REVENUE) / 1000000)) AS DECIMAL(38,0))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'App Engagement' AS TITLE, KPI_APP_ENGAGEMENT AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_APP_ENGAGEMENT)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
