-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Guest Experience 360
-- ============================================================================
USE DATABASE GUEST_EXPERIENCE;
USE SCHEMA ML;

-- ML.FORECAST: SATISFACTION_FORECAST
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.SATISFACTION_FORECAST(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.PROPERTY_NPS_TRENDS'),
  SERIES_COLNAME => 'PROPERTY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.SATISFACTION_FORECAST_RESULTS AS
SELECT * FROM TABLE(ML.SATISFACTION_FORECAST!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: SENTIMENT_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.SENTIMENT_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.GUEST_SENTIMENT_SCORES'),
  SERIES_COLNAME => 'PROPERTY_ID',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.SENTIMENT_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.SENTIMENT_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.GUEST_SENTIMENT_SCORES'), SERIES_COLNAME => 'PROPERTY_ID', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

