-- ============================================================================
-- 99_RESET.SQL — Reset Guest Experience 360 to clean demo state
-- ============================================================================
USE DATABASE GUEST_EXPERIENCE;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_ANALYZE_REVIEWS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_GENERATE_PERSONALIZATION SUSPEND;
ALTER TASK IF EXISTS APP.TASK_SEND_COMMUNICATIONS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.GUEST_SENTIMENT_SCORES REFRESH;
ALTER DYNAMIC TABLE CURATED.GUEST_LIFETIME_VALUE REFRESH;
ALTER DYNAMIC TABLE CURATED.SERVICE_RECOVERY_QUEUE REFRESH;
ALTER DYNAMIC TABLE CURATED.PROPERTY_NPS_TRENDS REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM GUEST_EXPERIENCE.RAW.GUEST_REVIEWS → 200000
-- SELECT COUNT(*) FROM GUEST_EXPERIENCE.RAW.GUEST_PROFILES → 180000
-- SELECT COUNT(*) FROM GUEST_EXPERIENCE.CURATED.SERVICE_RECOVERY_QUEUE → ~342

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_SEND_COMMUNICATIONS RESUME;
ALTER TASK IF EXISTS APP.TASK_GENERATE_PERSONALIZATION RESUME;
ALTER TASK IF EXISTS APP.TASK_ANALYZE_REVIEWS RESUME;
